{"uuid": "dbdfa7b0-87b6-4f11-afa2-5f2d8fa38cbd", "children": ["162c7c9f-195a-4cd8-b6fb-10a897e6d1d7"], "befores": [{"name": "create_pet", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='petstore.swagger.io', port=443): Max retries exceeded with url: /v2/pet (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000260BEF99F40>: Failed to resolve 'petstore.swagger.io' ([Errno 11002] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\Desktop\\project\\petstore\\tests\\conftest.py\", line 24, in create_pet\n    pet_info = petstore_client_v2.create_pet(pet_data)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\Desktop\\project\\petstore\\src\\api_clients\\petstore\\client.py\", line 18, in create_pet\n    response = self.post(path=Route.PET, json=pet_data, expected_status_code=expected_status_code)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\Desktop\\project\\petstore\\src\\base_clients\\http_client\\client.py\", line 20, in post\n    response = self._send_request(path=path, method=\"post\", json=json, expected_status_code=expected_status_code)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\Desktop\\project\\petstore\\src\\base_clients\\http_client\\client.py\", line 38, in _send_request\n    response = requests.request(method=method, url=url, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "steps": [{"name": "Send POST to https://petstore.swagger.io/v2/pet", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='petstore.swagger.io', port=443): Max retries exceeded with url: /v2/pet (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x00000260BEF99F40>: Failed to resolve 'petstore.swagger.io' ([Errno 11002] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\Kham2\\Desktop\\project\\petstore\\src\\base_clients\\http_client\\client.py\", line 38, in _send_request\n    response = requests.request(method=method, url=url, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Kham2\\PycharmProjects\\petstore\\.venv\\Lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1729612946714, "stop": 1729612946715}], "start": 1729612946714, "stop": 1729612946716}], "start": 1729612946714, "stop": 1729612946793}